var stations = [
  {
    name: "adjuntas",
    display_name: "Adjuntas",
    coords: [18.1629, -66.7231],
    vwc_max: 0.521,
    geologicUnit: "Yauco Formation",
    soilUnit: "Los Guineos Clay",
    elevation: "1020m",
    slope: "45°",
    landslideSusceptibility: "Very High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
  },
  {
    name: "anasco",
    display_name: "Añasco",
    coords: [18.2844, -67.1424],
    vwc_max: 0.5,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "Very High",
    sensorDepths: "25cm, 50cm, 75cm, 100cm",
    dateInstalled: "Sep-2023",
    collaborator: "Private Landowner",
  },
  {
    name: "barranquitas",
    display_name: "Barranquitas",
    coords: [18.1886, -66.3071],
    vwc_max: 0.263,
    geologicUnit: "Robles Formation",
    soilUnit: "Caguabo Clay Loam",
    elevation: "540m",
    slope: "45°",
    landslideSusceptibility: "Very High",
    sensorDepths: "25cm, 53cm, 82cm, 100cm",
    dateInstalled: "Feb-2022",
    collaborator: "Para la Naturaleza",
  },
  {
    name: "cayey",
    display_name: "Cayey",
    coords: [18.111, -66.166],
    vwc_max: 0.492,
    geologicUnit: "Formation A",
    soilUnit: "Mucara Clay",
    elevation: "480m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "21cm, 42cm, 63cm, 84cm",
    dateInstalled: "Dec-2021",
    collaborator: "USGS Geomagnetic Observatory",
  },
  {
    name: "ciales",
    display_name: "Ciales",
    coords: [18.3367, -66.4682],
    vwc_max: 0.475,
    geologicUnit: "Rio Orocovis Formation, Avispa Lava Member",
    soilUnit: "Mucara Clay",
    elevation: "310m",
    slope: "30°",
    landslideSusceptibility: "Very High",
    sensorDepths: "22.5cm, 45cm, 67.5cm, 90cm",
    dateInstalled: "Feb-2022",
    collaborator: "Private Landowner",
  },
  {
    name: "lares",
    display_name: "Lares",
    coords: [18.2958, -66.8782],
    vwc_max: 0.495,
    geologicUnit: "Milagros Formation Breccia Member",
    soilUnit: "Morado Clay Loam",
    elevation: "250m",
    slope: "35°",
    landslideSusceptibility: "Very High",
    sensorDepths: "22cm, 44cm, 66cm, 88cm",
    dateInstalled: "Mar-2022",
    collaborator: "Private Landowner",
  },
  {
    name: "maricao",
    display_name: "Maricao",
    coords: [18.1823, -66.9818],
    vwc_max: 0.447,
    geologicUnit: "Porphyritic Hornblende Diorite",
    soilUnit: "Mucara Clay",
    elevation: "400m",
    slope: "40°",
    landslideSusceptibility: "Very High",
    sensorDepths: "33cm, 66cm, 99cm, 130cm",
    dateInstalled: "Dec-2022",
    collaborator: "Private Landowner",
  },
  {
    name: "maunabo",
    display_name: "Maunabo",
    coords: [18.0086, -65.9011],
    vwc_max: 0.372,
    geologicUnit: "San Lorenzo Granodiorite",
    soilUnit: "Pandura Very Stony Land Complex",
    elevation: "350m",
    slope: "35°",
    landslideSusceptibility: "Very High",
    sensorDepths: "27.5cm, 55cm, 77.5cm, 110cm",
    dateInstalled: "Feb-2022",
    collaborator: "Para la Naturaleza",
  },
  {
    name: "mayaguez",
    display_name: "Mayagüez",
    coords: [18.2013, -67.1397],
    vwc_max: 0.45,
    geologicUnit: "Maricao Formation",
    soilUnit: "Mucara Clay",
    elevation: "33m",
    slope: "40°",
    landslideSusceptibility: "Very High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "UPR Mayagüez",
  },
  {
    name: "naguabo",
    display_name: "Naguabo",
    coords: [18.2113, -65.7358],
    vwc_max: 0.439,
    geologicUnit: "Rio Blanco Quartz Diorite",
    soilUnit: "Pandura Loam",
    elevation: "370m",
    slope: "40°",
    landslideSusceptibility: "Very High",
    sensorDepths: "25cm, 50cm, 75cm, 100cm",
    dateInstalled: "July-2022",
    collaborator: "Private Landowner",
  },
  {
    name: "naranjito",
    display_name: "Naranjito",
    coords: [18.3, -66.25],
    vwc_max: 0.424,
    geologicUnit: "Rio Orocovis Group, Los Negros Formation",
    soilUnit: "Mucara Clay",
    elevation: "300m",
    slope: "45°",
    landslideSusceptibility: "Very High",
    sensorDepths: "25cm, 50cm, 75cm, 100cm",
    dateInstalled: "August-2022",
    collaborator: "Municipio de Naranjito",
  },
  {
    name: "orocovis",
    display_name: "Orocovis",
    coords: [18.23, -66.3883],
    vwc_max: 0.479,
    geologicUnit: "TBA",
    soilUnit: "TBA",
    elevation: "TBA",
    slope: "TBA",
    landslideSusceptibility: "TBA",
    sensorDepths: "25cm, 50cm, 75cm, 100cm",
    dateInstalled: "Apr-2024",
    collaborator: "Private Collaborator",
  },
  {
    name: "ponce",
    display_name: "Ponce",
    coords: [18.0111, -66.6141],
    vwc_max: 0.434,
    geologicUnit: "Lago Garzas Formation",
    soilUnit: "Caguabo Gravelly Clay Loam",
    elevation: "330m",
    slope: "35°",
    landslideSusceptibility: "Very High",
    sensorDepths: "25cm, 50cm, 75cm, 100cm",
    dateInstalled: "March-2023",
    collaborator: "Para la Naturaleza",
  },
  {
    name: "sanlorenzo",
    display_name: "San Lorenzo",
    coords: [18.1897, -65.9721],
    vwc_max: 0.485,
    geologicUnit: "Formation A",
    soilUnit: "Los Guineos Clay",
    elevation: "420m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "17.5cm, 35cm, 52.5cm, 70cm",
    dateInstalled: "Feb-2022",
    collaborator: "Para la Naturaleza",
  },
  {
    name: "toronegro",
    display_name: "Toro Negro",
    coords: [18.1723, -66.495],
    vwc_max: 0.483,
    geologicUnit: "Achiote Conglomerate",
    soilUnit: "Los Guineos - Maricao Association",
    elevation: "1200m",
    slope: "45°",
    landslideSusceptibility: "Very High",
    sensorDepths: "30cm, 50cm, 90cm, 100cm",
    dateInstalled: "2018",
    collaborator: "Departamento de Recursos Naturales e Ambientales",
  },
  {
    name: "utuado",
    display_name: "Utuado",
    coords: [18.2681, -66.7005],
    vwc_max: 0.45,
    geologicUnit: "Utuado Granodiorite",
    soilUnit: "Pellejas Clay Loam",
    elevation: "500m",
    slope: "40°",
    landslideSusceptibility: "Very High",
    sensorDepths: "27cm, 42cm, 57cm, 72cm",
    dateInstalled: "2018",
    collaborator: "Private Landowner",
  },
  {
    name: "yabucoa",
    display_name: "Yabucoa",
    coords: [18.0919, -65.8802],
    vwc_max: 0.372,
    geologicUnit: "San Lorenzo Granodiorite",
    soilUnit: "Pandura Loam",
    elevation: "260m",
    slope: "##°",
    landslideSusceptibility: "Very High",
    sensorDepths: "25cm, 50cm, 75cm, 100cm",
    dateInstalled: "Dec-2023",
    collaborator: "Private Landowner",
  },
  {
    name: "yauco",
    display_name: "Yauco",
    coords: [18.034, -66.8497],
    vwc_max: 0.492,
    geologicUnit: "Yauco Mudstone",
    soilUnit: "Maricao Clay",
    elevation: "770m",
    slope: "45°",
    landslideSusceptibility: "Very High",
    sensorDepths: "25cm, 50cm, 75cm, 100cm",
    dateInstalled: "Jan-2023",
    collaborator: "Private Landowner",
  },
];

export { stations };
