const stationData = {
    Adjuntas: {
      rainfall: 15,
      soilSaturation: "High",
      geologicUnit: "Granite",
      soilUnit: "Loam",
      elevation: 300,
      slope: "Moderate",
      landslideSusceptibility: "Low",
      dateInstalled: "2023-06-01",
    },
    Añasco: {
      rainfall: 10,
      soilSaturation: "Medium",
      geologicUnit: "Limestone",
      soilUnit: "Clay",
      elevation: 150,
      slope: "Low",
      landslideSusceptibility: "High",
      dateInstalled: "2022-09-15",
    },
    Barranquitas: {
      rainfall: 18,
      soilSaturation: "High",
      geologicUnit: "Slate",
      soilUnit: "Sandy loam",
      elevation: 400,
      slope: "High",
      landslideSusceptibility: "Medium",
      dateInstalled: "2023-01-20",
    },
    Cayey: {
      rainfall: 12,
      soilSaturation: "Low",
      geologicUnit: "Marble",
      soilUnit: "Silty clay",
      elevation: 250,
      slope: "Moderate",
      landslideSusceptibility: "Low",
      dateInstalled: "2023-03-10",
    },
    Ciales: {
      rainfall: 20,
      soilSaturation: "High",
      geologicUnit: "Quartzite",
      soilUnit: "Clay loam",
      elevation: 350,
      slope: "High",
      landslideSusceptibility: "High",
      dateInstalled: "2022-11-05",
    },
    Lares: {
      rainfall: 14,
      soilSaturation: "Medium",
      geologicUnit: "Shale",
      soilUnit: "Loamy sand",
      elevation: 280,
      slope: "Low",
      landslideSusceptibility: "Medium",
      dateInstalled: "2023-04-18",
    },
    Maricao: {
      rainfall: 16,
      soilSaturation: "Medium",
      geologicUnit: "Basalt",
      soilUnit: "Sandy clay",
      elevation: 320,
      slope: "Moderate",
      landslideSusceptibility: "Low",
      dateInstalled: "2022-12-30",
    },
    Maunabo: {
      rainfall: 8,
      soilSaturation: "Low",
      geologicUnit: "Gneiss",
      soilUnit: "Silica sand",
      elevation: 100,
      slope: "Low",
      landslideSusceptibility: "High",
      dateInstalled: "2023-02-14",
    },
    Mayagüez: {
      rainfall: 22,
      soilSaturation: "High",
      geologicUnit: "Sandstone",
      soilUnit: "Peat",
      elevation: 200,
      slope: "Moderate",
      landslideSusceptibility: "Medium",
      dateInstalled: "2022-10-10",
    },
    Naguabo: {
      rainfall: 9,
      soilSaturation: "Low",
      geologicUnit: "Limestone",
      soilUnit: "Clay loam",
      elevation: 50,
      slope: "Low",
      landslideSusceptibility: "Low",
      dateInstalled: "2023-05-25",
    },
    Naranjito: {
      rainfall: 11,
      soilSaturation: "Medium",
      geologicUnit: "Schist",
      soilUnit: "Silty clay loam",
      elevation: 380,
      slope: "High",
      landslideSusceptibility: "High",
      dateInstalled: "2022-08-20",
    },
    Orocovis: {
      rainfall: 13,
      soilSaturation: "Medium",
      geologicUnit: "Dolomite",
      soilUnit: "Sandy clay loam",
      elevation: 270,
      slope: "Moderate",
      landslideSusceptibility: "Medium",
      dateInstalled: "2023-07-05",
    },
    Ponce: {
      rainfall: 17,
      soilSaturation: "High",
      geologicUnit: "Conglomerate",
      soilUnit: "Peaty clay",
      elevation: 180,
      slope: "Low",
      landslideSusceptibility: "Low",
      dateInstalled: "2022-07-15",
    },
    "San Lorenzo": {
      rainfall: 19,
      soilSaturation: "High",
      geologicUnit: "Gabbro",
      soilUnit: "Silt loam",
      elevation: 320,
      slope: "Moderate",
      landslideSusceptibility: "Medium",
      dateInstalled: "2023-09-10",
    },
    "Toro Negro": {
      rainfall: 14,
      soilSaturation: "Medium",
      geologicUnit: "Andesite",
      soilUnit: "Loamy clay",
      elevation: 280,
      slope: "Moderate",
      landslideSusceptibility: "Low",
      dateInstalled: "2023-08-12",
    },
    Utuado: {
      rainfall: 16,
      soilSaturation: "High",
      geologicUnit: "Granodiorite",
      soilUnit: "Silty clay loam",
      elevation: 350,
      slope: "High",
      landslideSusceptibility: "High",
      dateInstalled: "2022-11-30",
    },
    Yabucoa: {
      rainfall: 7,
      soilSaturation: "Low",
      geologicUnit: "Quartz",
      soilUnit: "Peaty sand",
      elevation: 70,
      slope: "Low",
      landslideSusceptibility: "Low",
      dateInstalled: "2023-01-02",
    },
    Yauco: {
      rainfall: 12,
      soilSaturation: "Medium",
      geologicUnit: "Rhyolite",
      soilUnit: "Sandy silt",
      elevation: 220,
      slope: "Moderate",
      landslideSusceptibility: "Medium",
      dateInstalled: "2022-12-18"
    }
  }

export default stationData;