/**
 * Station information for various monitoring stations.
 * Each station object contains details such as name, coordinates, soil and geologic units, and more.
 * The "url-name" property is used for the website links.
 */

const stations = [
  {
    name: "adjuntas",
    "url-name": "adjuntas",
    display_name: "Adjuntas",
    coords: [18.147, -66.765],
    vwc_max: 0.521,
    geologicUnit: "Yauco Formation",
    soilUnit: "Los Guineos Clay",
    elevation: "1020m",
    slope: "45°",
    landslideSusceptibility: "Very High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Adjuntas.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "anasco",
    "url-name": "anasco",
    display_name: "Añasco",
    coords: [18.294, -67.051],
    vwc_max: 0.500,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Anasco.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "barranquitas",
    "url-name": "barranquitas",
    display_name: "Barranquitas",
    coords: [18.166, -66.300],
    vwc_max: 0.263,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Barranquitas.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "cayey",
    "url-name": "cayey",
    display_name: "Cayey",
    coords: [18.109, -66.151],
    vwc_max: 0.492,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Cayey.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "ciales",
    "url-name": "ciales",
    display_name: "Ciales",
    coords: [18.312, -66.469],
    vwc_max: 0.475,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Ciales.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "lares",
    "url-name": "lares",
    display_name: "Lares",
    coords: [18.248, -66.881],
    vwc_max: 0.495,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Lares.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "maricao",
    "url-name": "maricao",
    display_name: "Maricao",
    coords: [18.174, -67.031],
    vwc_max: 0.447,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Maricao.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "maunabo",
    "url-name": "maunabo",
    display_name: "Maunabo",
    coords: [18.035, -65.910],
    vwc_max: 0.372,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Maunabo.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "mayaguez",
    "url-name": "mayaguez",
    display_name: "Mayagüez",
    coords: [18.220, -67.144],
    vwc_max: 0.512,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Mayaguez.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "naguabo",
    "url-name": "naguabo",
    display_name: "Naguabo",
    coords: [18.255, -65.794],
    vwc_max: 0.439,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Naguabo.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "naranjito",
    "url-name": "naranjito",
    display_name: "Naranjito",
    coords: [18.296, -66.246],
    vwc_max: 0.424,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Naranjito.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "orocovis",
    "url-name": "orocovis",
    display_name: "Orocovis",
    coords: [18.177, -66.415],
    vwc_max: 0.479,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Orocovis.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "ponce",
    "url-name": "ponce",
    display_name: "Ponce",
    coords: [18.083, -66.660],
    vwc_max: 0.434,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Ponce.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "sanlorenzo",
    "url-name": "san-lorenzo",
    display_name: "San Lorenzo",
    coords: [18.089, -66.002],
    vwc_max: 0.485,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "San_Lorenzo.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "toronegro",
    "url-name": "toro-negro",
    display_name: "Toro Negro",
    coords: [18.158, -66.565],
    vwc_max: 0.5337,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Toro_Negro.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "utuado",
    "url-name": "utuado",
    display_name: "Utuado",
    coords: [18.280, -66.661],
    vwc_max: 0.450,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Utuado.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "yabucoa",
    "url-name": "yabucoa",
    display_name: "Yabucoa",
    coords: [18.110, -65.856],
    vwc_max: 0.372,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Yabucoa.jpeg",
    forecast: "Incoming Feature"
  },
  {
    name: "yauco",
    "url-name": "yauco",
    display_name: "Yauco",
    coords: [18.139, -66.881],
    vwc_max: 0.509,
    geologicUnit: "Río Blanco Fm.",
    soilUnit: "Consumo Clay",
    elevation: "185m",
    slope: "35°",
    landslideSusceptibility: "High",
    sensorDepths: "20cm, 40cm, 60cm, 80cm",
    dateInstalled: "Mar-2022",
    collaborator: "Departamento de Recursos Naturales y Ambientales",
    plot_name: "Yauco.jpeg",
    forecast: "Incoming Feature"
  }
];

export { stations };